/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqs.messages;

import org.junit.Test;
import static org.junit.Assert.*;

public class QueueATest {
    @Test public void testAppHasAGreeting() {
        QueueA classUnderTest = new QueueA();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
