/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqs.messages;

import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.*;

import java.util.List;


public class QueueA {

    public static final String queueName = "https://sqs.us-east-1.amazonaws.com/755897667361/Messages";

    public static void main(String[] args) {

        String queueUrl = queueName;

       final AmazonSQS sqsClient = AmazonSQSClientBuilder.defaultClient();

        // Send multiple messages to the queue
        SendMessageBatchRequest send_batch_request = new SendMessageBatchRequest()
                .withQueueUrl(queueUrl)
                .withEntries(
                        new SendMessageBatchRequestEntry(
                                "msg_1", "Hello from message 1"),
                        new SendMessageBatchRequestEntry(
                                "msg_2", "Hello from message 2")
                                .withDelaySeconds(10),
                        new SendMessageBatchRequestEntry(
                                "msg_3", "Third message")
                                .withDelaySeconds(10));

        sqsClient.sendMessageBatch(send_batch_request);

        List<Message> messages = sqsClient.receiveMessage(queueUrl).getMessages();

        System.out.println(messages.size());

        for(Message m : messages){
            System.out.println(m.getBody());
        }
    }


}

